name:                rotation
version:             0.1.0.0
github:              "akaneko3/RotationHaskell"
license:             BSD3
author:              "Jun Kudou"
maintainer:          "prog@akanekodou.mydns.jp"
copyright:           "2019 Jun Kudou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akaneko3/RotationHaskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  rotation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rotation

tests:
  rotation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rotation
